version: '3.8'
volumes:
  postgres-data:
  deps:
  _build:

services:
  web:
    build: .
    ports:
      - "4004:4000"
    volumes:
      - .:/app
      - deps:/app/deps
      - _build:/app/_build
    depends_on:
      - db
    env_file:
      - local.env
    tty: true
    stdin_open: true

  db:
    image: postgres:latest
    env_file:
      - local.env
    volumes:
      - postgres-data:/var/lib/postgresql/data
    ports:
      - "8001:5432"
